# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: listOfStrings
  type: object
  default:
  - dev
  - test
  - prod

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- ${{ each stage in parameters.listOfStrings }}:
  - stage: ${{ stage }}
    displayName: Build ${{ stage }}
    variables:
      - template: variables-${{ stage }}.yml

    jobs:
    - job: Build
      displayName: "Build Macro $(example), Runtime $[variables.example], Template ${{ variables.example }}"
      steps:
      - script: echo Build started on `date`
        displayName: 'Run a one-line script'
      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
      - script: echo Build completed on `date`
        displayName: 'Run a one-line script'
