parameters:
  - name: stages
    type: object
    default:
      - name: dev
        other: a
      - name: test
        other: b
      - name: prod
        other: c

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - ${{ each stage in parameters.stages }}:
      - stage: ${{ stage.name }}
        displayName: Build ${{ stage.name }}
        variables:
          - template: variables-${{ stage.name }}.yml

        jobs:
          - job: Build
            displayName: "Build ${{ variables.example }}" # Can't use Macro $(example) or Runtime $[variables.example] here
            steps:
              - checkout: none
              - script: echo Build completed on `date`
                displayName: "${{ stage.other }}"
